//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsAndBids.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarsAndBids.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction ID must be greater than 0.
        /// </summary>
        internal static string AuctionIdGreaterThanZero {
            get {
                return ResourceManager.GetString("AuctionIdGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction with id {0} not found!.
        /// </summary>
        internal static string AuctionNotFoundById {
            get {
                return ResourceManager.GetString("AuctionNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body style ID must be greater than 0.
        /// </summary>
        internal static string BodyStyleIdGreaterThanZero {
            get {
                return ResourceManager.GetString("BodyStyleIdGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body type is required.
        /// </summary>
        internal static string BodyStyleIdRequired {
            get {
                return ResourceManager.GetString("BodyStyleIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body style name must be at most 50 characters long.
        /// </summary>
        internal static string BodyStyleNameMaxLength {
            get {
                return ResourceManager.GetString("BodyStyleNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body style name is required.
        /// </summary>
        internal static string BodyStyleNameRequired {
            get {
                return ResourceManager.GetString("BodyStyleNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car ID must be greater than 0.
        /// </summary>
        internal static string CarIdGreaterThanZero {
            get {
                return ResourceManager.GetString("CarIdGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image with URL {0} not found!.
        /// </summary>
        internal static string CarImageNotFound {
            get {
                return ResourceManager.GetString("CarImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car with ID {0} not found..
        /// </summary>
        internal static string CarNotFoundById {
            get {
                return ResourceManager.GetString("CarNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified car status not found.
        /// </summary>
        internal static string CarStatusInvalid {
            get {
                return ResourceManager.GetString("CarStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat ID must be greater than 0..
        /// </summary>
        internal static string ChatIdGreaterThanZero {
            get {
                return ResourceManager.GetString("ChatIdGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat not found or user not in chat..
        /// </summary>
        internal static string ChatNotFoundOrUserNotInChat {
            get {
                return ResourceManager.GetString("ChatNotFoundOrUserNotInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current price can&apos;t be less than start price.
        /// </summary>
        internal static string CurrentPriceGTEStartPrice {
            get {
                return ResourceManager.GetString("CurrentPriceGTEStartPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified drivetrain type not found.
        /// </summary>
        internal static string DrivetrainInvalid {
            get {
                return ResourceManager.GetString("DrivetrainInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format.
        /// </summary>
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format.
        /// </summary>
        internal static string EmailInvalidFormat {
            get {
                return ResourceManager.GetString("EmailInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to toggle emoji. Please try again..
        /// </summary>
        internal static string EmojiToggleFailed {
            get {
                return ResourceManager.GetString("EmojiToggleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time must be after start time.
        /// </summary>
        internal static string EndTimeAfterStartTime {
            get {
                return ResourceManager.GetString("EndTimeAfterStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete attachments..
        /// </summary>
        internal static string FailedToDeleteAttachments {
            get {
                return ResourceManager.GetString("FailedToDeleteAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name can&apos;t be longer than 50 characters.
        /// </summary>
        internal static string FirstNameMaxLength {
            get {
                return ResourceManager.GetString("FirstNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id {0} must be greater than 0.
        /// </summary>
        internal static string IdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("IdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID is required.
        /// </summary>
        internal static string IdRequired {
            get {
                return ResourceManager.GetString("IdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only JPEG or PNG images are allowed.
        /// </summary>
        internal static string ImageInvalidFormat {
            get {
                return ResourceManager.GetString("ImageInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email or password.
        /// </summary>
        internal static string IncorectData {
            get {
                return ResourceManager.GetString("IncorectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid auction status.
        /// </summary>
        internal static string InvalidAuctionStatus {
            get {
                return ResourceManager.GetString("InvalidAuctionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format.
        /// </summary>
        internal static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid refresh token or user not found.
        /// </summary>
        internal static string InvalidRefresh {
            get {
                return ResourceManager.GetString("InvalidRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name can&apos;t be longer than 50 characters.
        /// </summary>
        internal static string LastNameMaxLength {
            get {
                return ResourceManager.GetString("LastNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make ID must be greater than 0.
        /// </summary>
        internal static string MakeIdGreaterThanZero {
            get {
                return ResourceManager.GetString("MakeIdGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make name must be at most 50 characters long.
        /// </summary>
        internal static string MakeNameMaxLength {
            get {
                return ResourceManager.GetString("MakeNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make name is required.
        /// </summary>
        internal static string MakeNameRequired {
            get {
                return ResourceManager.GetString("MakeNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture year can&apos;t be greater than the current year.
        /// </summary>
        internal static string ManufactureYearMax {
            get {
                return ResourceManager.GetString("ManufactureYearMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture year can&apos;t be earlier than 1900.
        /// </summary>
        internal static string ManufactureYearMin {
            get {
                return ResourceManager.GetString("ManufactureYearMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture year is required.
        /// </summary>
        internal static string ManufactureYearRequired {
            get {
                return ResourceManager.GetString("ManufactureYearRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum {0} attachments are allowed..
        /// </summary>
        internal static string MaxAttachmentsAllowed {
            get {
                return ResourceManager.GetString("MaxAttachmentsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message doesn&apos;t exist..
        /// </summary>
        internal static string MessageDoesNotExist {
            get {
                return ResourceManager.GetString("MessageDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message not found..
        /// </summary>
        internal static string MessageNotFound {
            get {
                return ResourceManager.GetString("MessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message content or attachments are required..
        /// </summary>
        internal static string MessageOrAttachmentsRequired {
            get {
                return ResourceManager.GetString("MessageOrAttachmentsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage can&apos;t be less than 0.
        /// </summary>
        internal static string MileageMin {
            get {
                return ResourceManager.GetString("MileageMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model ID must be greater than 0.
        /// </summary>
        internal static string ModelIdGreaterThanZero {
            get {
                return ResourceManager.GetString("ModelIdGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model is required.
        /// </summary>
        internal static string ModelIdRequired {
            get {
                return ResourceManager.GetString("ModelIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model name must be at most 50 characters long.
        /// </summary>
        internal static string ModelNameMaxLength {
            get {
                return ResourceManager.GetString("ModelNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model name is required.
        /// </summary>
        internal static string ModelNameRequired {
            get {
                return ResourceManager.GetString("ModelNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at most 20 characters long.
        /// </summary>
        internal static string NewPasswordMaxLength {
            get {
                return ResourceManager.GetString("NewPasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long.
        /// </summary>
        internal static string NewPasswordMinLength {
            get {
                return ResourceManager.GetString("NewPasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is required.
        /// </summary>
        internal static string NewPasswordRequired {
            get {
                return ResourceManager.GetString("NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more attachments not found..
        /// </summary>
        internal static string OneOrMoreAttachmentsNotFound {
            get {
                return ResourceManager.GetString("OneOrMoreAttachmentsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner is required.
        /// </summary>
        internal static string OwnerIdRequired {
            get {
                return ResourceManager.GetString("OwnerIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants count must be greater than 0..
        /// </summary>
        internal static string ParticipantsRequired {
            get {
                return ResourceManager.GetString("ParticipantsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t be longer than 20 characters.
        /// </summary>
        internal static string PasswordMaxLength {
            get {
                return ResourceManager.GetString("PasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters.
        /// </summary>
        internal static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile picture URL must be a valid URL.
        /// </summary>
        internal static string ProfilePictureUrlInvalid {
            get {
                return ResourceManager.GetString("ProfilePictureUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile picture URL is too long.
        /// </summary>
        internal static string ProfilePictureUrlMaxLength {
            get {
                return ResourceManager.GetString("ProfilePictureUrlMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token has expired.
        /// </summary>
        internal static string RefreshExpired {
            get {
                return ResourceManager.GetString("RefreshExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token is required.
        /// </summary>
        internal static string RefreshTokenRequired {
            get {
                return ResourceManager.GetString("RefreshTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset token is required.
        /// </summary>
        internal static string ResetTokenRequired {
            get {
                return ResourceManager.GetString("ResetTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller ID must be greater than 0.
        /// </summary>
        internal static string SellerIdGreaterThanZero {
            get {
                return ResourceManager.GetString("SellerIdGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender ID is required..
        /// </summary>
        internal static string SenderIdRequired {
            get {
                return ResourceManager.GetString("SenderIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed must be greater than 0.
        /// </summary>
        internal static string SpeedsGreaterThanZero {
            get {
                return ResourceManager.GetString("SpeedsGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start price must be greater than 0.
        /// </summary>
        internal static string StartPriceGreaterThanZero {
            get {
                return ResourceManager.GetString("StartPriceGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time must be before end time.
        /// </summary>
        internal static string StartTimeBeforeEndTime {
            get {
                return ResourceManager.GetString("StartTimeBeforeEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time must be in the future.
        /// </summary>
        internal static string StartTimeInFuture {
            get {
                return ResourceManager.GetString("StartTimeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified transmission type not found.
        /// </summary>
        internal static string TransmissionTypeInvalid {
            get {
                return ResourceManager.GetString("TransmissionTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with {0} already exists!
        ///.
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has already seen this message..
        /// </summary>
        internal static string UserAlreadySeenMessage {
            get {
                return ResourceManager.GetString("UserAlreadySeenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can&apos;t read his own message..
        /// </summary>
        internal static string UserCannotReadOwnMessage {
            get {
                return ResourceManager.GetString("UserCannotReadOwnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID must be greater than 0.
        /// </summary>
        internal static string UserIdGreaterThanZero {
            get {
                return ResourceManager.GetString("UserIdGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can&apos;t be longer than 30 characters.
        /// </summary>
        internal static string UsernameMaxLength {
            get {
                return ResourceManager.GetString("UsernameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be at least 4 characters.
        /// </summary>
        internal static string UsernameMinLength {
            get {
                return ResourceManager.GetString("UsernameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        internal static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized to delete attachment {0}..
        /// </summary>
        internal static string UserNotAuthorizedToDeleteAttachment {
            get {
                return ResourceManager.GetString("UserNotAuthorizedToDeleteAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t have rights to delete this message..
        /// </summary>
        internal static string UserNotAuthorizedToDeleteMessage {
            get {
                return ResourceManager.GetString("UserNotAuthorizedToDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized to edit the message..
        /// </summary>
        internal static string UserNotAuthorizedToEditMessage {
            get {
                return ResourceManager.GetString("UserNotAuthorizedToEditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not a participant of this chat..
        /// </summary>
        internal static string UserNotInChat {
            get {
                return ResourceManager.GetString("UserNotInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not a participant of this chat..
        /// </summary>
        internal static string UserNotParticipantOfChat {
            get {
                return ResourceManager.GetString("UserNotParticipantOfChat", resourceCulture);
            }
        }
    }
}
